import PDFDocument from 'pdfkit';
import { ErpPdfSettings } from '../invoicing/erp-invoice-pdf';

const safeParse = (s: any): any[] => {
  if (Array.isArray(s)) return s;
  try { return JSON.parse(s || '[]'); } catch { return []; }
};

/**
 * Render an e-way bill to a PDF Buffer in the standard GST **EWB-01** layout —
 * the same shape the Vyapar / commercial billing apps produce: a header with the
 * EWB number + validity, PART-A (document + bill-from/to + value), PART-B
 * (transport: mode/vehicle/route/distance) and a goods-details table pulled from
 * the linked invoice. This is a local/printable copy; statutory e-way generation
 * still happens on the government portal (needs the NIC API).
 */
export function buildEwayBillPdf(e: any, invoice: any | null, s: ErpPdfSettings): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: 'A4', margin: 36 });
      const chunks: Buffer[] = [];
      doc.on('data', (c: Buffer) => chunks.push(c));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      const cur = (s.currency || 'INR') === 'INR' ? 'Rs.' : (s.currency || '');
      const money = (n: any) => `${cur} ${Number(n || 0).toFixed(2)}`;
      const date = (d: any) => (d ? new Date(d).toLocaleDateString('en-IN') : '-');
      const left = 36, right = 559, W = right - left;
      let y = 36;

      // ── Title bar ──────────────────────────────────────────────────────
      doc.rect(left, y, W, 44).fillAndStroke('#f3f4f6', '#999');
      doc.fillColor('#111').fontSize(18).text('e-Way Bill', left + 12, y + 8);
      doc.fontSize(8).fillColor('#666').text('Standard format (GST EWB-01)', left + 12, y + 30);
      doc.fontSize(8).fillColor('#666').text('EWB No.', right - 200, y + 8, { width: 190, align: 'right' });
      doc.fontSize(15).fillColor('#111').text(String(e.eway_number || '-'), right - 200, y + 20, { width: 190, align: 'right' });
      y += 44;

      const section = (title: string) => {
        doc.rect(left, y, W, 16).fillAndStroke('#eef2f7', '#999');
        doc.fillColor('#111').fontSize(9).text(title, left + 8, y + 4);
        y += 16;
      };
      const kv2 = (l1: string, v1: any, l2?: string, v2?: any) => {
        doc.rect(left, y, W, 18).stroke('#cccccc');
        doc.fontSize(7.5).fillColor('#777').text(l1, left + 8, y + 4, { width: 78 });
        doc.fontSize(9).fillColor('#111').text(String(v1 ?? '-'), left + 88, y + 4, { width: 190, ellipsis: true, height: 12 });
        if (l2) {
          doc.fontSize(7.5).fillColor('#777').text(l2, left + 292, y + 4, { width: 78 });
          doc.fontSize(9).fillColor('#111').text(String(v2 ?? '-'), left + 372, y + 4, { width: W - 372 + left - 8, ellipsis: true, height: 12 });
        }
        y += 18;
      };

      // ── 1. e-Way bill details ──────────────────────────────────────────
      section('1. e-Way Bill Details');
      kv2('Generated On', date(e.created_at), 'Valid Until', date(e.valid_until));
      kv2('Status', String(e.status || 'active').toUpperCase(), 'Approx Dist.', `${Number(e.distance_km) || 0} km`);
      kv2('Generated By', s.businessName, 'GSTIN', s.gstin || '-');
      if (s.address) kv2('Address', s.address);

      // ── 2. Part-A ──────────────────────────────────────────────────────
      section('2. Part-A');
      kv2('Document No', invoice?.invoice_number || e.invoice_number || '-', 'Doc Date', date(invoice?.issued_at || invoice?.created_at || e.created_at));
      kv2('Bill From', s.businessName, 'From GSTIN', s.gstin || '-');
      kv2('Bill To', invoice?.customer_name || '-', 'To Phone', invoice?.customer_phone || '-');
      kv2('Value of Goods', money(e.value), 'Reason', 'Supply');
      kv2('Transporter', e.transporter || '-');

      // ── 3. Part-B ──────────────────────────────────────────────────────
      section('3. Part-B (Transportation)');
      kv2('Mode', String(e.transport_mode || 'road').toUpperCase(), 'Vehicle No', e.vehicle_number || '-');
      kv2('From', e.from_place || '-', 'To', e.to_place || '-');

      // ── 4. Goods details (from the linked invoice) ─────────────────────
      // Columns fit inside [left, right]; Amount is right-aligned and ends
      // 6px before the right border so nothing spills out of the table.
      section('4. Goods Details');
      const cDesc = left + 8, wDesc = 208;
      const cHsn = left + 224, wHsn = 46;
      const cQty = left + 276, wQty = 44;
      const cRate = left + 326, wRate = 78;
      const cAmt = left + 410, wAmt = right - (left + 410) - 6;
      doc.rect(left, y, W, 16).fillAndStroke('#f3f4f6', '#cccccc');
      doc.fillColor('#111').fontSize(8);
      doc.text('Description', cDesc, y + 4, { width: wDesc });
      doc.text('HSN', cHsn, y + 4, { width: wHsn });
      doc.text('Qty', cQty, y + 4, { width: wQty, align: 'right' });
      doc.text('Rate', cRate, y + 4, { width: wRate, align: 'right' });
      doc.text('Amount', cAmt, y + 4, { width: wAmt, align: 'right' });
      y += 16;

      const items = invoice ? safeParse(invoice.items) : [];
      doc.fillColor('#333').fontSize(8);
      if (items.length) {
        for (const it of items) {
          const qty = Number(it.quantity || 0);
          const rate = Number(it.unitPrice ?? it.unit_price ?? 0);
          const amt = Number(it.lineTotal ?? it.line_total ?? qty * rate);
          doc.rect(left, y, W, 16).stroke('#eeeeee');
          doc.fillColor('#333');
          doc.text(String(it.description || it.name || '-'), cDesc, y + 4, { width: wDesc, ellipsis: true, height: 10 });
          doc.text(String(it.hsn || it.hsnCode || '-'), cHsn, y + 4, { width: wHsn });
          doc.text(String(qty), cQty, y + 4, { width: wQty, align: 'right' });
          doc.text(money(rate), cRate, y + 4, { width: wRate, align: 'right' });
          doc.text(money(amt), cAmt, y + 4, { width: wAmt, align: 'right' });
          y += 16;
          if (y > 760) { doc.addPage(); y = 40; }
        }
      } else {
        doc.rect(left, y, W, 16).stroke('#eeeeee');
        doc.fillColor('#777').text('Value of goods as per linked invoice', cDesc, y + 4, { width: 360 });
        doc.fillColor('#111').text(money(e.value), cAmt, y + 4, { width: wAmt, align: 'right' });
        y += 16;
      }

      // Total
      doc.rect(left, y, W, 18).fillAndStroke('#f9fafb', '#cccccc');
      doc.fillColor('#111').fontSize(9).text('Total Value', left + 8, y + 5);
      doc.text(money(e.value), cAmt, y + 5, { width: wAmt, align: 'right' });
      y += 26;

      // ── Footer ─────────────────────────────────────────────────────────
      doc.fontSize(7).fillColor('#999').text(
        'System-generated e-way bill in the standard EWB-01 format. For statutory use, generate/validate on the government portal (ewaybillgst.gov.in).',
        left, y, { width: W, align: 'center' },
      );
      doc.fontSize(7).fillColor('#bbb').text('Generated via WhatsApp Commerce ERP', left, y + 18, { width: W, align: 'center' });

      doc.end();
    } catch (err) {
      reject(err as Error);
    }
  });
}
