import { chromium } from 'playwright-core';
const browser = await chromium.connectOverCDP('http://127.0.0.1:9222');
const ctx = browser.contexts()[0];
const page = ctx.pages()[0] ?? await ctx.newPage();
const errs = [];
page.on('console', (m) => { if (m.type() === 'error') errs.push(m.text().slice(0, 300)); });
page.on('pageerror', (e) => errs.push('PAGEERROR: ' + String(e).slice(0, 400)));
await page.goto('http://127.0.0.1:43110/entry/receipt', { waitUntil: 'networkidle' }).catch(() => {});
await page.waitForTimeout(2000);
console.log('URL:', page.url());
console.log('BODY text len:', (await page.textContent('body'))?.trim().length);
errs.slice(0, 8).forEach((e) => console.log('ERR:', e));
await browser.close();
